### ISSUE TITLE
Question - reproduce memory leak

### ISSUE THREAD

**Issue by dselivanov** [wch/fastmap#1]
Hi @wch. Thank you for opening up interesting problem with maps in R. 

I'm curious, how can I reproduce  following?
> However, this method is problematic when using a large set of keys or randomly-generated keys, because each time you use a key or even check for the existence of a key using exists(), that key is interned as a symbol and stored in the R symbol table, which is never garbage-collected. This means that every time you use a new key -- whether it is to store an object or just check whether the key exists in the environment, R leaks a little memory.

**Comment by wch** [comment]
@dselivanov Good question. I've added some examples to the bottom of the README that illustrate the problem.
