### ISSUE TITLE
Default container for map

### ISSUE THREAD

**Issue by dselivanov** [wch/fastmap#2]
Mb makes sense to use `unordered_map` because of better complexity O(1) compared to O(log n) for 
`map` ? Is C++98 support the reason for choosing `map` over `unordered_map`?

**Comment by jimhester** [comment]
I agree that `unordered_map()` seems preferable unless you need the strict ordering when iterating over the keys.

If C++98 support is required there is `[boost::unordered_map()] and also `std::tr1::unordered_map()`.

Also if you could use C++11 maybe think about using something like <https://github.com/greg7mdp/parallel-hashmap>, which has improved performance over the stdlib implementations.

**Comment by wch** [comment]
Unfortunately, there are still some platforms out there that don't support C++11. I also don't want to bring in a BH dependency.

The good news is that the change is very simple, so I was able to `typedef` it to either `unordered_map` or `map`, depending on the compiler's C++11 support. (811ea85)

There's a performance increase for calling `set()`: it went from about 470ms in my test, down to 340ms. Below are screenshots of the tests with profvis.

Before:
![image](https://user-images.githubusercontent.com/86978/57633401-27b99380-7569-11e9-9a2a-430492f2432f.png)

After:
![image](https://user-images.githubusercontent.com/86978/57633409-2be5b100-7569-11e9-88a3-2cfd19a8828d.png)
